# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name_plural': '用户类型表'},
        ),
    ]
