# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171214_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='caption',
            new_name='name',
        ),
    ]
